package models;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ArtTest {
    @Test
    void testGettingASCIIArtByPassingKeyValue_shouldReturnStringRepresentationOfImage() {
        assertEquals("\n $$$$$$\\             $$\\           $$$$$$$\\  $$\\           $$\\              $$$$$$\\                  $$$$$$$\\  $$\\                 $$$$$$$$\\                  $$\\                     \n$$  __$$\\            $$ |          $$  __$$\\ \\__|          $$ |            $$  __$$\\                 $$  __$$\\ \\__|                \\__$$  __|                 \\__|                    \n$$ /  \\__| $$$$$$\\ $$$$$$\\         $$ |  $$ |$$\\  $$$$$$$\\ $$$$$$$\\        $$ /  $$ | $$$$$$\\        $$ |  $$ |$$\\  $$$$$$\\           $$ | $$$$$$\\  $$\\   $$\\ $$\\ $$$$$$$\\   $$$$$$\\  \n$$ |$$$$\\ $$  __$$\\\\_$$  _|        $$$$$$$  |$$ |$$  _____|$$  __$$\\       $$ |  $$ |$$  __$$\\       $$ |  $$ |$$ |$$  __$$\\          $$ |$$  __$$\\ $$ |  $$ |$$ |$$  __$$\\ $$  __$$\\ \n$$ |\\_$$ |$$$$$$$$ | $$ |          $$  __$$< $$ |$$ /      $$ |  $$ |      $$ |  $$ |$$ |  \\__|      $$ |  $$ |$$ |$$$$$$$$ |         $$ |$$ |  \\__|$$ |  $$ |$$ |$$ |  $$ |$$ /  $$ |\n$$ |  $$ |$$   ____| $$ |$$\\       $$ |  $$ |$$ |$$ |      $$ |  $$ |      $$ |  $$ |$$ |            $$ |  $$ |$$ |$$   ____|         $$ |$$ |      $$ |  $$ |$$ |$$ |  $$ |$$ |  $$ |\n\\$$$$$$  |\\$$$$$$$\\  \\$$$$  |      $$ |  $$ |$$ |\\$$$$$$$\\ $$ |  $$ |       $$$$$$  |$$ |            $$$$$$$  |$$ |\\$$$$$$$\\          $$ |$$ |      \\$$$$$$$ |$$ |$$ |  $$ |\\$$$$$$$ |\n \\______/  \\_______|  \\____/       \\__|  \\__|\\__| \\_______|\\__|  \\__|       \\______/ \\__|            \\_______/ \\__| \\_______|         \\__|\\__|       \\____$$ |\\__|\\__|  \\__| \\____$$ |\n                                                                                                                                                    $$\\   $$ |              $$\\   $$ |\n                                                                                                                                                    \\$$$$$$  |              \\$$$$$$  |\n                                                                                                                                                     \\______/                \\______/ \nWelcome to Get Rich Or Die Trying.\n\nAt a young age you realize that you want to be a millionaire.\nYour mission is to make $1 million before all your health points run out.\n\nEach choice you make will affect your net worth and health levels.\n\nPress any key to continue.", Art.getArt("welcome"));
    }
}